"""Host-aware web egress policy for restricted practice modes."""

import os
import re
import shutil
import subprocess
import tempfile
from pathlib import Path

PROXY_CONFIG = Path("/run/gallos/squid.conf")
_HOST = re.compile(
    r"^(?=.{1,253}$)[a-z0-9](?:[a-z0-9-]*[a-z0-9])?"
    r"(?:\.[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)+$"
)


def effective_websites(mode: str, config: dict) -> list[str]:
    """Event inherits Default browsing limits unless it explicitly overrides them."""
    if mode == "Event":
        return config.get("event", {}).get(
            "allowed_websites", config.get("default", {}).get("allowed_websites", [])
        )
    return config.get(mode.lower(), {}).get("allowed_websites", [])


def validate_website_list(sites: list[str]) -> list[str]:
    """Require literal DNS names; wildcard/IP/URL tokens are unsafe in proxy ACLs."""
    clean = []
    for site in sites:
        name = site.strip().lower()
        if not _HOST.fullmatch(name) or all(part.isdigit() for part in name.split(".")):
            raise ValueError(f"Invalid restricted website hostname: {site}")
        clean.append(name)
    if not clean:
        raise ValueError("Restricted website list cannot be empty")
    return sorted(set(clean))


def build_squid_config(sites: list[str]) -> str:
    """Render an exact-host explicit proxy with no disk cache or general tunnel."""
    names = validate_website_list(sites)
    return f"""# Generated by gallosd for the active restricted mode.
http_port 127.0.0.1:3128
visible_hostname gallosos
cache deny all
access_log none
cache_log /dev/null
pid_filename none
acl gallos_local src 127.0.0.1/32
acl SSL_ports port 443
acl Safe_ports port 80 443
acl CONNECT method CONNECT
acl gallos_sites dstdomain {" ".join(names)}
http_access deny !gallos_local
http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports
http_access allow gallos_local gallos_sites
http_access deny all
"""


def apply_web_egress(mode: str, config: dict) -> None:
    """Apply the restricted proxy lifecycle for the active mode."""
    sites = effective_websites(mode, config)
    if mode == "Contest" or not sites or sites == ["*"]:
        subprocess.run(["systemctl", "stop", "gallos-web-proxy.service"], check=True, timeout=20)
        return
    content = build_squid_config(sites)
    PROXY_CONFIG.parent.mkdir(parents=True, exist_ok=True)
    fd, candidate = tempfile.mkstemp(prefix="squid-", suffix=".conf", dir=PROXY_CONFIG.parent)
    backup = None
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as stream:
            stream.write(content)
        os.chmod(candidate, 0o644)
        subprocess.run(["squid", "-k", "parse", "-f", candidate], check=True, timeout=10)
        if PROXY_CONFIG.exists():
            backup_fd, backup = tempfile.mkstemp(prefix="squid-backup-", dir=PROXY_CONFIG.parent)
            os.close(backup_fd)
            shutil.copy2(PROXY_CONFIG, backup)
        os.replace(candidate, PROXY_CONFIG)
        try:
            subprocess.run(
                ["systemctl", "restart", "gallos-web-proxy.service"], check=True, timeout=20
            )
        except Exception:
            if backup is not None:
                os.replace(backup, PROXY_CONFIG)
                backup = None
                subprocess.run(
                    ["systemctl", "restart", "gallos-web-proxy.service"], check=False, timeout=20
                )
            else:
                PROXY_CONFIG.unlink(missing_ok=True)
            raise
    finally:
        if os.path.exists(candidate):
            os.unlink(candidate)
        if backup is not None and os.path.exists(backup):
            os.unlink(backup)
